# Generated by Django 3.2.25 on 2024-10-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='SAMPLES/default_profile_qdjgyp', upload_to='SAMPLES/'),
        ),
    ]
